services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      # HTTP Router (for redirecting to HTTPS)
      - "traefik.http.routers.frontend-http.rule=Host(`cfiles.localhost`) || Host(`localhost`)"
      - "traefik.http.routers.frontend-http.middlewares=httpsredirect"

      # HTTPS Router for Frontend
      - "traefik.http.routers.frontend-https.rule=Host(`cfiles.localhost`) || Host(`localhost`)"
      - "traefik.http.routers.frontend-https.entrypoints=websecure"
      - "traefik.http.routers.frontend-https.tls=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000" # Define the service here
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - cfiles-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      # Service definition
      - "traefik.http.services.backend.loadbalancer.server.port=8000"

      # --- HTTPS Routers (HTTP is handled by global redirect) ---
      # Backend API (HTTPS)
      - "traefik.http.routers.backend-api-https.rule=(Host(`cfiles.localhost`) || Host(`localhost`)) && PathPrefix(`/api`)"

      - "traefik.http.routers.backend-api-https.entrypoints=websecure"
      - "traefik.http.routers.backend-api-https.tls=true"
      - "traefik.http.routers.backend-api-https.middlewares=api-stripprefix"
      - "traefik.http.routers.backend-api-https.service=backend"

      # Backend WebSocket (HTTPS)
      - "traefik.http.routers.backend-ws-https.rule=(Host(`cfiles.localhost`) || Host(`localhost`)) && PathPrefix(`/ws`)"

      - "traefik.http.routers.backend-ws-https.entrypoints=websecure"
      - "traefik.http.routers.backend-ws-https.tls=true"
      - "traefik.http.routers.backend-ws-https.service=backend"

      # --- Middlewares ---
      - "traefik.http.middlewares.api-stripprefix.stripprefix.prefixes=/api"
    volumes:
      - ./backend:/app
      - ./testfiles:/files
      - ./uploads:/uploads
      - ./quarantine:/quarantine
    networks:
      - cfiles-network
    depends_on:
      - rabbitmq
      - clamav
      - postgres
    env_file:
      - ./.env

  workers:
    build:
      context: .
      dockerfile: ./workers/Dockerfile
    networks:
      - cfiles-network
    depends_on:
      - rabbitmq
      - postgres
      - clamav
    volumes:
      - ./testfiles:/files
      - ./uploads:/uploads
      - ./quarantine:/quarantine
    env_file:
      - ./.env

  rabbitmq:
    image: rabbitmq:3-management
    env_file:
      - ./.env
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - cfiles-network

  postgres:
    image: postgres:latest
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cfiles-network

  clamav:
    image: clamav/clamav:latest
    container_name: clamav
    ports:
      - "3310:3310"
    restart: always
    healthcheck:
      test: ["CMD", "clamdscan", "--version"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./testfiles:/files
      - ./uploads:/uploads
      - ./quarantine:/quarantine
    networks:
      - cfiles-network

  traefik:
    image: traefik:v2.9
    container_name: traefik-cfiles
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Traefik Dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
      - "./traefik/traefik.yml:/etc/traefik/traefik.yml:ro"
    networks:
      - cfiles-network

networks:
  cfiles-network:
    driver: bridge

volumes:
  postgres-data:
  letsencrypt:
